### ISSUE TITLE
README instructions for loader

### ISSUE THREAD

**Issue by fiznool** [webpack-contrib/svg-inline-loader#53]
Is there a reason that the README specifies the following instructions? I couldn't get it to work without appending `-loader` to the `svg-inline` key.

``` js
    {
        test: /\.svg$/,
        loader: 'svg-inline'
    }
```

**Comment by sairion** [comment]
It is just because I haven't used Webpack 2, appending `-loader` is a must in Webpack 2. It should be fixed 😃
